apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: evaluate-task
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: copy-scripts
      image: docker.io/bouinchafatima/mlops
      script: |
        #!/bin/sh
        mkdir -p $(workspaces.shared-workspace.path)/scripts
        cp -r /app/scripts/* $(workspaces.shared-workspace.path)/scripts/
    - name: evaluate
      image: docker.io/bouinchafatima/mlops
      workingDir: $(workspaces.shared-workspace.path)/scripts
      script: |
        #!/bin/sh
        python evaluate.py
