apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: iris-pipeline-run-
spec:
  pipelineRef:
    name: mlops-pipeline
  params:
  - name: gitRevision
    value: "abc123def456789"
  - name: appGitUrl
    value: 'git@github.com:fatima-bouincha/mlops-tekton.git'
  - name: datasetPath
    value: ./scripts/iris.csv
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: mlops-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
  taskRunTemplate:
    serviceAccountName: tekton-github-sa