apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: mlops-pipelinerun
spec:
  pipelineRef:
    name: mlops-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: mlops-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
