# event-listener.yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener-interceptor
spec:
  serviceAccountName: tekton-github-sa
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-trigger-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
      bindings:
      - ref: push-github-binding
      template:
        ref: push-github-template
