apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-gitlab-sa
  namespace: default
secrets:
- name: gitlab-trigger-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-gitlab-binding
subjects:
- kind: ServiceAccount
  name: tekton-gitlab-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-gitlab-triggers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-gitlab-triggers
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets", "serviceaccounts"]
  verbs: ["create", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

