apiVersion: v1
kind: Service
metadata:
  name: iris-pipeline-listener-service
spec:
  selector:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: gitlab-listener-interceptor
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort