apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: tekton-triggers
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "tekton.local.test"
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tekton-triggers
  namespace: default
spec:
  hosts:
  - "tekton.local.test"
  gateways:
  - tekton-triggers
  http:
  - route:
    - destination:
        host: el-github-listener-interceptor
        port:
          number: 8080
---